### PR TITLE
Move source classes to the `Yoast\WHIPv2` namespace

### PR DESCRIPTION
**Pull request by enricobattocchi**
Also includes backslashing of the global namespace functions.

### CODE REVIEW

**Review by jrfnl — COMMENTED** [review]
@enricobattocchi I've looked this over.

As mentioned on Slack, the directory names need to be updated to match the namespace in a case-sensitive manner.
Looks like you made this change already, but only for the directories containing namespaced classes, which makes the directory structure inconsistent, so I propose to _also_ apply this for the directories containing plain files. 

Another thing is that, yes, you've added namespaces, but the prefixing which was applied to the classes (for lack of namespacing) was not removed.

The class prefixing is no longer needed now and as this change is going into a major release, now would be the time to remove it.

I'll push some commits in a minute to fix this all up and apply some minor changes to the PHPCS config as well.

Let me know what you think.

**Comment by enricobattocchi** [comment]
Looks good to me!

**Comment by jrfnl** [comment]
> Looks good to me!

@enricobattocchi To keep the history cleaner, shall I squash those rename commits ? (or will you ?) I mostly did them one class at the time to make sure I didn't miss anything, but these don't really need separate commits.

**Comment by enricobattocchi** [comment]
On it!

**Pull request merged**
